# Site Settings
title:               STRIDER
tagline:             Autonomous Rover for Education
description:
baseurl:            "/STRIDER"
url:                "https://svanimisetti.in"
enforce_ssl:        "svanimisetti.in"
github:
  url:               "https://svanimisetti.in/STRIDER"
author:
  name:              "Sampath Vanimisetti"
  email:             "sampath.vanimisetti@gmail.com"
  twitter:           "svanimisetti"
  instagram:
  github:            "svanimisetti"
  facebook:
  linkedin:          "sampathvanimisetti"
navigation:
- title: About
  url: /about
- title: Writing
  url: /writing
- title: Contact
  url: /contact

paginate:            5
disqus:              svanimisetti

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
